language: c
fast_finish: true

os:
  - linux
  - osx
  
env: FC=gfortran

dist: trusty
group: edge

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    packages: 
      - gfortran

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update;
      brew install gcc || true;
      brew link --overwrite gcc;
    fi

install: 
    - cd bin
    - cmake ../src
    
script:
    - make

