language: generic
sudo: required
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

os:
  - linux
  - osx

env: FC=gfortran-6

addons:
  apt:
    packages:
      - gfortran

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update;
      brew install gcc || brew link --overwrite gcc > /dev/null;
    else
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
      sudo apt-get update -q;
      sudo apt-get install -yq gfortran-6;
    fi

install:
  - cd bin
  - cmake ../src
  - cmake --build .

script:
  - ctest -V
