language: c
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: gfortran-6

matrix:
  include:
  - os: linux
    env: FC=gfortran-6
#  - os: osx
#    before_install:
 #   - brew update > /dev/null
 #   - brew install gcc > /dev/null
  - os: windows
    install:
    - cd build
    - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ../src
    - cmake --build .

install:
  - cd $TRAVIS_BUILD_DIR/build
  - cmake ../src
  - cmake --build .

script: ctest --output-on-failure

