      SUBROUTINE CARRY(OBJECT,WHER)
      USE ALLCOM
      implicit none
!     START TOTING AN OBJECT, REMOVING IT FROM THE LIST OF THINGS AT ITS FORMER LOCATION.
!     IF OBJECT>MAXOBJ (MOVING "FIXED" SECOND LOC),DON'T CHANGE PLACE.

      INTEGER, intent(in) :: OBJECT,WHER
      integer TEMP

      IF (OBJECT<=MAXOBJ) THEN
         IF (PLACE(OBJECT)==-1) RETURN
         PLACE(OBJECT)=-1
      ENDIF
      IF (ATLOC(WHER)==OBJECT) THEN
         ATLOC(WHER)=LINK(OBJECT)
      ELSE
         TEMP=ATLOC(WHER)

7     IF (LINK(TEMP)/=OBJECT) THEN
            TEMP=LINK(TEMP)
            IF (TEMP/=0) GO TO 7
            CALL BUG('TRYING TO CARRY A NON-EXISTENT OBJECT')
         ENDIF

         LINK(TEMP)=LINK(OBJECT)
      ENDIF
      END subroutine carry