INTEGER FUNCTION CLASS(WORD)
implicit none
!     RETURNS WORD CLASS NUMBER (1=MOTION VERB; 2=NOUN; 3=ACTION VERB;
!     4=MISCELLANEOUS WORD; 5=PREPOSITION; 6=ADJECTIVE; 7=CONJUNCTION).

INTEGER, intent(in) :: WORD

CLASS=WORD/1000 +1
IF (WORD<0) CLASS=-1
END function class