SUBROUTINE DROP(OBJECT,WHER)
USE ALLCOM, only: fixed,place,maxobj,atloc,link
implicit none
!     PLACE OBJECT AT A GIVEN LOC, PREFIXING IT ONTO THE ATLOC LIST.

INTEGER, intent(in) :: OBJECT,WHER

IF (OBJECT>MAXOBJ) THEN
  FIXED(OBJECT-MAXOBJ)= WHER
ELSE
  PLACE(OBJECT)=WHER
ENDIF

IF (WHER>0) THEN
  LINK(OBJECT)=ATLOC(WHER)
  ATLOC(WHER)=OBJECT
ENDIF
END subroutine drop