   SUBROUTINE DROP(OBJECT,WHERE)
      USE ALLCOM

!     PLACE OBJECT AT A GIVEN LOC, PREFIXING IT ONTO THE ATLOC LIST.
      
      INTEGER OBJECT,WHERE

      IF (OBJECT.GT.MAXOBJ) THEN
         FIXED(OBJECT-MAXOBJ)=WHERE
      ELSE
         PLACE(OBJECT)=WHERE
      ENDIF

      IF (WHERE.GT.0) THEN
         LINK(OBJECT)=ATLOC(WHERE)
         ATLOC(WHERE)=OBJECT
      ENDIF
      END