   SUBROUTINE INSERT(OBJECT,CONTNR)
      USE ALLCOM
      
      INTEGER OBJECT,CONTNR,TEMP

      IF (CONTNR.EQ.OBJECT) CALL BUG('TRYING TO PUT A CONTAINER INTO ITSELF)')
      CALL CARRY(OBJECT,LOC)

      TEMP=HOLDER(CONTNR)
      HOLDER(CONTNR)=OBJECT
      HLINK(OBJECT)=TEMP
      PLACE(OBJECT)=-CONTNR

      END