INTEGER FUNCTION LJUST(LINE,QUOT)

  IMPLICIT NONE

  INTEGER I,L

!     SQUEEZES OUT BLANKS EXCEPT THOSE WITHIN QUOTES. IF QUOTE IS BLANK, ONLY SQUEEZES OUT LEADING AND EXTRA BLANKS

  CHARACTER(*) LINE, QUOT

  LOGICAL PRIME

  LJUST=0
  PRIME = .FALSE.
  L=LEN_TRIM(LINE)
  DO I=1,L
     IF (LINE(I:I).EQ.QUOT .AND. QUOT.NE.' ') PRIME = .NOT. PRIME
     IF (LINE(I:I) .NE. ' ' .OR. PRIME) THEN
        LJUST=LJUST+1
        IF (LJUST.NE.I) LINE(LJUST:LJUST)=LINE(I:I)
        IF (QUOT .EQ. ' ') PRIME=LINE(I:I) .NE. ' '
     ENDIF
  END DO
  IF (LJUST < L) LINE(LJUST+1:L)=' '
10 I=INDEX(LINE,' ,')
  IF (I.GT.0) THEN
     LINE(I:)=LINE(I+1:)
     GO TO 10
  ENDIF
END function ljust