   SUBROUTINE LOOKIN(CONTNR)
      USE ALLCOM

!     LIST CONTENTS IF OBJECT IS A CONTAINER AND IS OPEN OR TRANSPARENT. SAVE INITIAL VALUE OF BLKLIN SUBROUTINE.

      INTEGER CONTNR,TEMP,LOOP,SPKSAVE
      
      LOGICAL VESSEL,AJAR,OPAQUE,BSAVE

      IF (.NOT.VESSEL(CONTNR).OR.(.NOT.AJAR(CONTNR).AND.OPAQUE(CONTNR)) )RETURN
      TEMP=HOLDER(CONTNR)
      LOOP=0
      BSAVE=BLKLIN
      SPKSAVE=SPK
      DO WHILE (TEMP.NE.0)
         BLKLIN=.FALSE.
         IF (LOOP.EQ.0) CALL SPEAK(RTEXT(360))
         INDENT=1
         CALL PSPEAK(TEMP,-1)
         BLKLIN=BSAVE
         TEMP=HLINK(TEMP)
         LOOP=-1
      END DO
      SPK=SPKSAVE

      END