SUBROUTINE MOVE(OBJECT,WHER)
  USE ALLCOM
  implicit none
!     PLACE OBJECT BY PICKING IT UP AND DROPPING IT.  MAY ALREADY BE TOTING, IN WHICH CASE THE CARRY IS A NO-OP.
!     MUSTN'T PICK UP OBJECTS WHICH ARE NOT AT ANY LOC, SINCE CARRY WANTS TO REMOVE OBJECTS FROM ATLOC CHAINS.

  INTEGER, intent(in) :: OBJECT,WHER
  integer FROM
  LOGICAL,external :: ENCLSD

  IF (OBJECT > MAXOBJ) THEN
     FROM=FIXED(OBJECT-MAXOBJ)
  ELSE
     IF (ENCLSD(OBJECT)) CALL REMOVE(OBJECT)
     FROM=PLACE(OBJECT)
  ENDIF
  IF (FROM>0 .AND. FROM <= MAXOBJ*2) CALL CARRY(OBJECT,FROM)
  CALL DROP(OBJECT,WHER)
END subroutine move