   SUBROUTINE NOT_TOTING_SPK(ISFIXED)
      USE ALLCOM
      LOGICAL ISFIXED
      INTEGER NOWAY
      SPK=NOWAY()
      
      IF (OBJ.EQ.PLANT.AND.PROP(PLANT).LE.0) SPK=115
      IF (OBJ.EQ.BEAR.AND.PROP(BEAR).EQ.1) SPK=169
      IF (OBJ.EQ.CHAIN.AND.PROP(BEAR).NE.0) SPK=170
      IF (OBJ.EQ.SWORD.AND.PROP(SWORD).EQ.5) SPK=208
      IF (OBJ.EQ.CLOAK.AND.PROP(CLOAK).EQ.2) SPK=242
      IF (OBJ.EQ.AXE.AND.PROP(AXE).EQ.2) SPK=246
      IF (OBJ.EQ.PHONE) SPK=251
      IF (OBJ.EQ.BEES.OR.OBJ.EQ.HIVE) SPK=295
      IF (OBJ.EQ.STICKS) SPK=296
      IF (OBJ.NE.0) ISFIXED=FIXED(OBJ).NE.0
      END