   SUBROUTINE PSPEAK(MSG,SKIP)
      USE ALLCOM

!     FIND THE SKIP+1ST MESSAGE FROM MSG AND PRINT IT.  MSG SHOULD BE THE INDEX OF
!     THE INVENTORY MESSAGE FOR OBJECT.  (INVEN+N+1 MESSAGE IS PROP=N MESSAGE).

      INTEGER M,I,SKIP,MSG

      M=PTEXT(MSG)
      IF (SKIP.GE.0) THEN
         DO I=0,SKIP
   1        M=IABS(LINES(M))
            IF (LINES(M).GE.0) GO TO 1
         END DO
      ENDIF
      CALL SPEAK(M)
      END