SUBROUTINE REMOVE(OBJECT)
  USE ALLCOM
  implicit none

  integer, intent(in) :: OBJECT
  INTEGER CONTNR,TEMP

  CONTNR=-PLACE(OBJECT)
  PLACE(OBJECT)=-1

  IF (HOLDER(CONTNR).EQ.OBJECT) THEN
     HOLDER(CONTNR)=HLINK(OBJECT)
  ELSE
     TEMP=HOLDER(CONTNR)
     DO WHILE (HLINK(TEMP).NE.OBJECT)
        TEMP=HLINK(TEMP)
     END DO
     HLINK(TEMP)=HLINK(OBJECT)
  ENDIF
END subroutine remove