   SUBROUTINE SOUND(WHAT)
      USE WINMM 
      IMPLICIT NONE
      INTEGER(BOOL) :: RET
      CHARACTER WHAT*(*),FILE*256
      FILE='SOUNDS\'//WHAT//'.WAV'//CHAR(0)
      RET = PLAYSOUND(FILE, NULL, SND_FILENAME)
      END