   SUBROUTINE WAIT(TIME)
      IMPLICIT NONE
      REAL(4) TIME,TIME_BEGIN,TIME_END
      CALL CPU_TIME(TIME_BEGIN)
      DO
         CALL CPU_TIME(TIME_END)
         IF (TIME_END-TIME_BEGIN.GT. TIME) EXIT
      END DO
   END